<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/AndOperator_tensorflow_ver2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [2]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

In [3]:
y = np.array([
              [0],
              [0],
              [0],
              [1]
], dtype = 'float32')

In [4]:
model = Sequential()
model.add(Dense(1, input_dim = 2, activation = 'sigmoid')) # Dense(출력할 칸, input_dim = 입력할 칸, activation => 선형 회귀 후 sigmoid 함수)

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(lr=0.1), metrics = ['acc']) # metrics에 acc쓰면 accuracy도 구해줌, Adam() learning_rate 설정

In [8]:
model.fit(X, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7691 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7387 - acc: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7096 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6816 - acc: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6549 - acc: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6294 - acc: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6051 - acc: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5820 - acc: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5600 - acc: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5391 - acc: 0.5000
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5192 

In [9]:
model.layers[0].get_weights() # w와 b를 보여줌

[array([[4.3245068],
        [4.0009775]], dtype=float32), array([-6.3623853], dtype=float32)]

In [10]:
w = model.layers[0].get_weights()[0]
b = model.layers[0].get_weights()[1]

In [11]:
tf.sigmoid(tf.matmul(X, w) + b)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.00172231],
       [0.08616328],
       [0.11528289],
       [0.876868  ]], dtype=float32)>

In [13]:
pred = model.predict(X); pred

array([[0.00172231],
       [0.08616328],
       [0.11528289],
       [0.876868  ]], dtype=float32)

In [14]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [15]:
pred = pred.flatten() # 1차원 배열로 만들어줌

array([0.00172231, 0.08616328, 0.11528289, 0.876868  ], dtype=float32)

In [17]:
y = y.flatten()

In [18]:
pred03 = (pred == y)
acc = np.sum(pred03)/4
acc

0.0