<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/AndOperation_tensorflow_1_X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
import numpy as np

In [4]:
tf.enable_eager_execution()
print(tf.__version__)

1.15.2


In [5]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [0],
              [0],
              [1]
], dtype = 'float32')

In [6]:
w = tf.Variable([[1], [2]], dtype = 'float32')
b = tf.Variable([3], dtype = 'float32')

In [7]:
# tf.matmul(X, w) : X와 w의 곱을 계산
tf.matmul(X, w) + b

<tf.Tensor: id=19, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)>

In [8]:
tf.sigmoid(tf.matmul(X,w) + b)

<tf.Tensor: id=25, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)>

In [9]:
# w와 b값을 자동으로 수정하는 Optimizer 객체를 생성
optimizer = tf.train.AdamOptimizer(0.01)

In [11]:
for step in range(1000):
  with tf.GradientTape() as tape:
    # 로지스틱 회귀(= perceptron) 식을 변수 hypothesis에 대입
    # tf.matmul : 배열끼리의 곱을 계산하는 함수
    # tf.matmul(X, w) + b : X와 w의 곱을 계산하고 b를 더함
    hypothesis = tf.sigmoid(tf.matmul(X, w) + b)
    # tf.reduce_mean() -> 평균을 계산
    cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
    # cost, w, b를 이용해서 w의 기울기. b의 기울기를 계산해서 grads 대입
    grads = tape.gradient(cost, [w, b])
  optimizer.apply_gradients(grads_and_vars = zip(grads, [w, b]))

  if step % 100 == 0:
    print('='*100)
    print('step : {}, cost : {}, w : {}, b : {}'.format(step, cost.numpy(), w.numpy(), b.numpy()))
    print('='*100)

step : 0, cost : 3.0067431926727295, w : [[0.98000014]
 [1.9800001 ]], b : [2.98]
step : 100, cost : 1.8424098491668701, w : [[0.00187232]
 [0.9919162 ]], b : [1.9934133]
step : 200, cost : 1.082991123199463, w : [[-0.71547705]
 [ 0.17880608]], b : [1.1276144]
step : 300, cost : 0.8442481160163879, w : [[-0.76826847]
 [-0.11236401]], b : [0.5206295]
step : 400, cost : 0.7191399931907654, w : [[-0.44732547]
 [-0.03626965]], b : [0.05765341]
step : 500, cost : 0.6168594360351562, w : [[-0.0678472 ]
 [ 0.16496052]], b : [-0.3615094]
step : 600, cost : 0.5330392122268677, w : [[0.28079495]
 [0.3999162 ]], b : [-0.75882936]
step : 700, cost : 0.465332955121994, w : [[0.58824867]
 [0.64070547]], b : [-1.1349852]
step : 800, cost : 0.4105614423751831, w : [[0.8612028]
 [0.8773646]], b : [-1.4898765]
step : 900, cost : 0.3657488226890564, w : [[1.1078681]
 [1.1057427]], b : [-1.8251848]


In [12]:
predict = tf.sigmoid(tf.matmul(X, w) + b)
predict

<tf.Tensor: id=63187, shape=(4, 1), dtype=float32, numpy=
array([[0.10524059],
       [0.30619514],
       [0.30841887],
       [0.6259348 ]], dtype=float32)>

In [13]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
print('predict01')
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [14]:
ac01 = tf.equal(predict01, y)
ac01

<tf.Tensor: id=63192, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [15]:
ac02 = tf.cast(ac01, dtype = 'float32')
ac02

<tf.Tensor: id=63193, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [16]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=63195, shape=(), dtype=float32, numpy=1.0>

In [18]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
print('accuracy')
print(accuracy.numpy())

accuracy
1.0


In [19]:
arr = np.array([[0, 1]], dtype = 'float32')
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict

<tf.Tensor: id=63211, shape=(1, 1), dtype=float32, numpy=array([[0.30619514]], dtype=float32)>

In [20]:
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)

In [21]:
arr = np.array([[1, 1]], dtype = 'float32')
predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict

<tf.Tensor: id=63220, shape=(1, 1), dtype=float32, numpy=array([[0.6259348]], dtype=float32)>

In [22]:
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict.numpy()

array([[1.]], dtype=float32)