<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/AndOperator_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y = np.array([
              [0],
              [0],
              [0],
              [1]
], dtype = 'float32'); y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [5]:
w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

In [7]:
np.dot(X, w) + b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [8]:
def sigmoid(h):
  return 1/(1+np.exp(-h))

In [9]:
hypothesis = np.dot(X, w) + b

In [10]:
hypothesis = sigmoid(hypothesis); hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [11]:
hypothesis - y

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [40]:
 X_col_2d1 = X.T[0].reshape(1, -1) # reshape(줄, 칸) 여기서 하나의 값만 알고 있으면 하나는 모르고 있어도 알아서 만듦
 X_col_2d1

array([[0., 0., 1., 1.]], dtype=float32)

In [41]:
X_col_2d2 = X.T[1].reshape(1, -1)
X_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [42]:
w1_gred = 1/4 * np.sum(np.dot(X_col_2d1, (hypothesis - y)))
w1_gred

0.24488529562950134

In [43]:
w2_gred = 1/4 * np.sum(np.dot(X_col_2d2, (hypothesis - y)))
w2_gred

0.24770864844322205

In [44]:
learning_rate = 0.1

In [45]:
w[0] = w[0] - w1_gred * learning_rate

In [46]:
w[0]

array([0.951023], dtype=float32)

In [47]:
w[1] = w[1] - w2_gred * learning_rate

In [48]:
w[1]

array([1.9752291], dtype=float32)

In [49]:
b_gred = 1/4 * np.sum(hypothesis - y)
b_gred

0.731355607509613

In [57]:
'''
tensorflow를 쓰지 않고 AndOperator 계산
for문 사용
'''
import numpy as np
import time
start = time.time()
def sigmoid(h):
  return 1/(1+np.exp(-h))

X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [0],
              [0],
              [1]
], dtype = 'float32')
learning_rate = 0.1

w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

for i in range(1000):
  for j in range(2):
    hypothesis = sigmoid(np.dot(X, w) + b)
    print('hypothesis :\n', hypothesis)
    cost = -1/4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
    print('cost :\n', cost)
    X_col_2d = X.T[j].reshape(1, -1)
    w_gred = 1/4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
    print('{}번째 시도 => w_gred : {}'.format(i, w_gred))
    w[j] = w[j] - learning_rate * w_gred
    print('w{} :{}'.format(j, w[j]))
    b_gred = 1/4 * np.sum(hypothesis - y)
    print('{}번째 시도 => b_gred : {}'.format(i, b_gred))
    b = b - learning_rate * b_gred
    print('b:{}'.format(b))

print('걸린 시간 : {:.0f}초'.format(time.time() - start))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
hypothesis :
 [[0.00538598]
 [0.12950248]
 [0.12468849]
 [0.7964786 ]]
cost :
 [[0.00135014]
 [0.03467259]
 [0.03329387]
 [0.05688874]]
821번째 시도 => w_gred : -0.01850472390651703
w1 :[3.3150408]
821번째 시도 => b_gred : 0.014013893902301788
b:[-5.219957]
hypothesis :
 [[0.00537848]
 [0.1295531 ]
 [0.12453562]
 [0.79655135]]
cost :
 [[0.00134825]
 [0.03468712]
 [0.03325021]
 [0.05686592]]
822번째 시도 => w_gred : -0.01972825825214386
w0 :[3.2717671]
822번째 시도 => b_gred : 0.014004632830619812
b:[-5.2213573]
hypothesis :
 [[0.00537099]
 [0.12939525]
 [0.12459804]
 [0.79664415]]
cost :
 [[0.00134636]
 [0.0346418 ]
 [0.03326802]
 [0.0568368 ]]
822번째 시도 => w_gred : -0.018490150570869446
w1 :[3.3168898]
822번째 시도 => b_gred : 0.014002107083797455
b:[-5.2227573]
hypothesis :
 [[0.00536352]
 [0.12944582]
 [0.12444544]
 [0.79671687]]
cost :
 [[0.00134449]
 [0.03465631]
 [0.03322445]
 [0.05681398]]
823번째 시도 => w_gred : -0.019709423184394836
w0 :[3.2737381]
823번째 시도 => b_gr

In [58]:
w

array([[3.5944264],
       [3.6230006]], dtype=float32)

In [59]:
b

array([-5.684683], dtype=float32)

In [60]:
np.dot(X, w) + b

array([[-5.684683 ],
       [-2.0616822],
       [-2.0902565],
       [ 1.5327444]], dtype=float32)

In [61]:
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.00338611],
       [0.11287727],
       [0.11004746],
       [0.8224075 ]], dtype=float32)

In [62]:
# np.where(조건, 조건만족시 리턴값, 조건불만족시 리턴값)
predict01 = np.where(predict >= 0.5, 1, 0)
print('predict01')
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [63]:
# predict01 == y가 같으면 true 다르면 false 리턴
predict02 = (predict01 == y)
predict02

array([[ True],
       [ True],
       [ True],
       [ True]])

In [64]:
np.sum(predict02)

4

In [65]:
acc = np.sum(predict02)/4
acc

1.0

In [66]:
'''
tensorflow를 쓰지 않고 AndOperator 계산
for문 사용
정확도까지 표시
'''
import numpy as np
import time
start = time.time()
def sigmoid(h):
  return 1/(1+np.exp(-h))

X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [0],
              [0],
              [1]
], dtype = 'float32')
learning_rate = 0.1

w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

for i in range(1000):
  for j in range(2):
    hypothesis = sigmoid(np.dot(X, w) + b)
    cost = -1/4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
    X_col_2d = X.T[j].reshape(1, -1)
    w_gred = 1/4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
    w[j] = w[j] - learning_rate * w_gred
    b_gred = 1/4 * np.sum(hypothesis - y)
    b = b - learning_rate * b_gred

print('걸린 시간 : {:.0f}초'.format(time.time() - start))

predict = sigmoid(np.dot(X, w) + b)
predict01 = np.where(predict >= 0.5, 1, 0)
predict02 = (predict01 == y)
acc = np.sum(predict02)/4
print('정확도 :', acc)

걸린 시간 : 0초
정확도 : 1.0
