<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/Cancer_tensorflowVer1_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
tf.enable_eager_execution() # w와 b가 어떻게 변하는지 보려는 것

In [3]:
data = datasets.load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [4]:
X = data.data
X = np.array(X, dtype = 'float32') # tensorflow는 64까지는 계산을 못하기 때문에 32로 바꿔줘야함
y = data.target
y = np.array(y, dtype = 'float32')

In [7]:
np.round(X)

array([[ 18.,  10., 123., ...,   0.,   0.,   0.],
       [ 21.,  18., 133., ...,   0.,   0.,   0.],
       [ 20.,  21., 130., ...,   0.,   0.,   0.],
       ...,
       [ 17.,  28., 108., ...,   0.,   0.,   0.],
       [ 21.,  29., 140., ...,   0.,   0.,   0.],
       [  8.,  25.,  48., ...,   0.,   0.,   0.]], dtype=float32)

In [8]:
y = y.reshape(1, -1)

In [9]:
y # 행이 하나고 열이 데이터 수만큼 생김

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
        0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
        1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 

In [10]:
X.shape

(569, 30)

In [11]:
y.shape # 이러면 X와 안맞음

(1, 569)

In [13]:
y = y.reshape(-1, 1)
y.shape # 이러면 X와 맞음

(569, 1)

In [14]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 777)

In [24]:
np.round(X_train)

array([[ 13.,  28.,  86., ...,   0.,   0.,   0.],
       [ 20.,  20., 134., ...,   0.,   0.,   0.],
       [ 23.,  27., 154., ...,   0.,   0.,   0.],
       ...,
       [  9.,  16.,  59., ...,   0.,   0.,   0.],
       [  9.,  15.,  59., ...,   0.,   0.,   0.],
       [ 10.,  19.,  64., ...,   0.,   0.,   0.]], dtype=float32)

In [25]:
X_train.mean()

62.806488

In [26]:
X_train.std()

231.03027

In [32]:
# 데이터의 범위를 맞추기 위해서 평균을 빼고 표준편차로 나눔 (x - u) / std = z
# 하지만 이렇게 해버리면 실제 값이 달라짐
# 이유는 각 칼럼마다 mean과 std를 따로 계산해야하는데 전체 데이터의 평균과 표준편차로 구해버려서 값이 달라짐
np.round((X_train - X_train.mean()) / X_train.std(), 0)

array([[-0., -0.,  0., ..., -0., -0., -0.],
       [-0., -0.,  0., ..., -0., -0., -0.],
       [-0., -0.,  0., ..., -0., -0., -0.],
       ...,
       [-0., -0., -0., ..., -0., -0., -0.],
       [-0., -0., -0., ..., -0., -0., -0.],
       [-0., -0.,  0., ..., -0., -0., -0.]], dtype=float32)

In [36]:
np.round(((X_train - X_train.mean()) / X_train.std()).mean(), 0) # 정규화해서 평균은 0

0.0

In [35]:
np.round(((X_train - X_train.mean()) / X_train.std()).std(), 0) # 정규화해서 표준편차는 1

1.0

In [45]:
# 0번째 칸의 평균
X_train.T[0].mean()

14.246725

In [46]:
# 각 칼럼의 평균
X_train.mean(axis = 0)

array([1.4246725e+01, 1.9343344e+01, 9.2774887e+01, 6.6597266e+02,
       9.6632332e-02, 1.0508492e-01, 9.0719335e-02, 5.0065666e-02,
       1.8118951e-01, 6.2786199e-02, 4.0612021e-01, 1.2142562e+00,
       2.8748589e+00, 4.0316635e+01, 7.0176283e-03, 2.5348747e-02,
       3.2062460e-02, 1.1764454e-02, 2.0531220e-02, 3.7363092e-03,
       1.6416775e+01, 2.5748188e+01, 1.0823849e+02, 8.9480145e+02,
       1.3245043e-01, 2.5506768e-01, 2.7562380e-01, 1.1570261e-01,
       2.9101664e-01, 8.3712734e-02], dtype=float32)

In [47]:
# 각 칼럼의 표준편차
X_train.std(axis = 0)

array([3.5674140e+00, 4.3507361e+00, 2.4575031e+01, 3.5615921e+02,
       1.4353688e-02, 5.3791646e-02, 8.1841223e-02, 3.9670683e-02,
       2.7552009e-02, 7.2733620e-03, 2.6560730e-01, 5.5348390e-01,
       1.9292133e+00, 4.1717815e+01, 3.0911560e-03, 1.8196652e-02,
       3.1977080e-02, 6.1692162e-03, 8.5335122e-03, 2.6235476e-03,
       4.8489132e+00, 6.1664410e+00, 3.3675991e+01, 5.6701605e+02,
       2.2961164e-02, 1.5849927e-01, 2.1007721e-01, 6.5664366e-02,
       6.4403780e-02, 1.7722715e-02], dtype=float32)

In [48]:
np.round((X_train - X_train.mean(axis = 0)) / X_train.std(axis = 0)) # 이렇게하면 skicit에서 제공하는 StandardScaler와 동일

array([[-0.,  2., -0., ..., -1., -0., -1.],
       [ 2.,  0.,  2., ...,  2.,  0., -0.],
       [ 3.,  2.,  2., ...,  2.,  0.,  0.],
       ...,
       [-1., -1., -1., ..., -1., -2., -0.],
       [-2., -1., -1., ..., -1., -1.,  1.],
       [-1.,  0., -1., ..., -0., -0.,  0.]], dtype=float32)

In [37]:
from sklearn.preprocessing import StandardScaler

In [80]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
np.round(X_train)

array([[-0.,  2., -0., ..., -1., -0., -1.],
       [ 2.,  0.,  2., ...,  2.,  0., -0.],
       [ 3.,  2.,  2., ...,  2.,  0.,  0.],
       ...,
       [-1., -1., -1., ..., -1., -2., -0.],
       [-2., -1., -1., ..., -1., -1.,  1.],
       [-1.,  0., -1., ..., -0., -0.,  0.]], dtype=float32)

In [81]:
X_train

array([[-0.22053097,  2.0379677 , -0.2801584 , ..., -0.8816444 ,
        -0.33564335, -0.73931825],
       [ 1.6631867 ,  0.0452016 ,  1.6693815 , ...,  1.5472225 ,
         0.18917061, -0.16717093],
       [ 2.512541  ,  1.7529584 ,  2.471008  , ...,  2.1868389 ,
         0.29941234,  0.17250594],
       ...,
       [-1.4847522 , -0.82361716, -1.3849382 , ..., -1.1763248 ,
        -1.9535606 , -0.36635056],
       [-1.5021317 , -1.0810449 , -1.3829037 , ..., -1.0331726 ,
        -1.018833  ,  1.3929741 ],
       [-1.2251801 ,  0.01302284, -1.1729344 , ..., -0.2773593 ,
        -0.44743806,  0.06699167]], dtype=float32)

In [49]:
def sigmoid(h):
  return 1 / (1 + np.exp(-h))

In [50]:
# tf.contrib.layers.xavier_initializer() : w와 b를 초기화 시키는 객체를 생성
initializer = tf.contrib.layers.xavier_initializer()

In [55]:
# 30줄 1칸의 w를 생성
w = tf.Variable(initializer([30, 1]))

In [74]:
# 하나의 값 b에 생성
b = tf.Variable(initializer([1]))

In [82]:
# 선형회귀 결과
tf.matmul(X_train, w) + b

<tf.Tensor: id=226, shape=(455, 1), dtype=float32, numpy=
array([[ 1.7296635e+00],
       [-1.6636556e+00],
       [-3.3631144e+00],
       [-5.2828968e-01],
       [ 8.0934519e-01],
       [ 6.9885248e-01],
       [-1.5740980e+00],
       [-8.3556789e-01],
       [ 8.4688425e-01],
       [-4.8709035e-02],
       [ 6.8711448e-01],
       [-6.6178125e-01],
       [-1.8618442e+00],
       [-9.9331737e-01],
       [ 5.1165032e-01],
       [-6.6496909e-02],
       [ 8.3636779e-01],
       [ 6.2092400e-01],
       [-7.1216983e-01],
       [-1.1317114e+00],
       [-1.8254073e+00],
       [ 4.0130681e-01],
       [-8.6114907e-01],
       [ 1.0042591e+00],
       [-3.0145307e+00],
       [ 1.2866089e+00],
       [-2.5972265e-01],
       [ 9.7650349e-01],
       [ 1.3020225e+00],
       [ 1.9339808e+00],
       [ 1.9725327e-01],
       [-2.2718654e+00],
       [-1.4024010e+00],
       [ 1.1226096e+00],
       [-7.5759420e+00],
       [ 9.3147099e-02],
       [ 2.5600284e-01],
       [ 2.153800

In [83]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
hypothesis

<tf.Tensor: id=232, shape=(455, 1), dtype=float32, numpy=
array([[8.49369407e-01],
       [1.59271866e-01],
       [3.34683657e-02],
       [3.70915890e-01],
       [6.91969931e-01],
       [6.67933285e-01],
       [1.71632975e-01],
       [3.02469075e-01],
       [6.99913085e-01],
       [4.87825155e-01],
       [6.65324688e-01],
       [3.40339601e-01],
       [1.34488255e-01],
       [2.70257354e-01],
       [6.25193238e-01],
       [4.83381897e-01],
       [6.97699666e-01],
       [6.50428653e-01],
       [3.29119563e-01],
       [2.43845403e-01],
       [1.38786256e-01],
       [5.99001586e-01],
       [2.97099322e-01],
       [7.31895089e-01],
       [4.67736721e-02],
       [7.83572674e-01],
       [4.35431898e-01],
       [7.26413846e-01],
       [7.86175132e-01],
       [8.73689413e-01],
       [5.49154043e-01],
       [9.34799612e-02],
       [1.97435409e-01],
       [7.54472435e-01],
       [5.12361526e-04],
       [5.23269951e-01],
       [5.63653469e-01],
       [8.9602333

In [84]:
optimizer = tf.train.AdamOptimizer(0.001)

In [86]:
for step in range(100):
  with tf.GradientTape() as tape:
    hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
    cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))
    grads = tape.gradient(cost, [w, b])
  optimizer.apply_gradients(grads_and_vars = zip(grads, [w,b]))

  if step % 10 == 0:
    print('=' * 50)
    print('step : {}, cost : {}, w : {}, b : {}'.format(step, cost.numpy(), w.numpy(), b.numpy()))
    print('=' * 50)

step : 0, cost : 0.4321812689304352, w : [[-0.27238783]
 [ 0.31783533]
 [-0.39419976]
 [-0.02114333]
 [ 0.11111461]
 [-0.4232727 ]
 [-0.05770699]
 [-0.11149405]
 [ 0.3244282 ]
 [-0.01339475]
 [-0.22433713]
 [-0.24258171]
 [ 0.1476333 ]
 [-0.20492521]
 [ 0.29961008]
 [ 0.31904864]
 [ 0.38065022]
 [-0.00363589]
 [-0.35024914]
 [-0.15994084]
 [-0.21705827]
 [ 0.29677874]
 [ 0.33077472]
 [-0.30267727]
 [ 0.41076326]
 [-0.32015786]
 [-0.17407732]
 [-0.29223055]
 [-0.15170078]
 [-0.10495121]], b : [0.08529443]
step : 10, cost : 0.3983449935913086, w : [[-0.2823417 ]
 [ 0.30786756]
 [-0.40415162]
 [-0.03109695]
 [ 0.10117383]
 [-0.43319654]
 [-0.06764463]
 [-0.12143904]
 [ 0.31449628]
 [-0.02316829]
 [-0.2342867 ]
 [-0.25250742]
 [ 0.13768934]
 [-0.21487577]
 [ 0.2896567 ]
 [ 0.30916813]
 [ 0.3707571 ]
 [-0.01355593]
 [-0.34017566]
 [-0.16971715]
 [-0.22701454]
 [ 0.28681034]
 [ 0.32082096]
 [-0.31263265]
 [ 0.4008064 ]
 [-0.33009294]
 [-0.18401715]
 [-0.30217785]
 [-0.1616522 ]
 [-0.11487705

In [92]:
X_test = scaler.transform(X_test)

In [93]:
predict = tf.sigmoid(tf.matmul(X_test, w) + b)
predict

<tf.Tensor: id=6684, shape=(114, 1), dtype=float32, numpy=
array([[9.69183922e-01],
       [9.65933681e-01],
       [8.33094120e-04],
       [8.12462866e-01],
       [3.47795784e-01],
       [6.23356998e-01],
       [8.87385368e-01],
       [9.69012976e-01],
       [9.03816044e-01],
       [2.52925158e-02],
       [4.61363316e-01],
       [7.80991316e-01],
       [9.66861844e-01],
       [1.48350835e-01],
       [6.98445499e-01],
       [9.02811885e-01],
       [9.45297241e-01],
       [9.10866022e-01],
       [8.64936173e-01],
       [8.41703415e-01],
       [8.02429199e-01],
       [1.01087540e-01],
       [2.03429759e-02],
       [7.96626687e-01],
       [9.05027986e-03],
       [9.82642412e-01],
       [9.65973973e-01],
       [4.92769480e-03],
       [2.27499604e-02],
       [8.68742466e-01],
       [4.40625489e-01],
       [8.09839368e-01],
       [9.08715606e-01],
       [9.00965095e-01],
       [9.61908817e-01],
       [7.78844833e-01],
       [2.11764574e-02],
       [3.151550

In [94]:
# tf.cast는 True는 1, False는 0으로 변환
predict = tf.cast(predict > 0.5, dtype = tf.float32)
predict

<tf.Tensor: id=6687, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
     

In [95]:
accuracy = tf.equal(y_test, predict)
accuracy = tf.cast(accuracy, dtype = 'float32')
accuracy = tf.reduce_mean(accuracy)  # tf.reduce_mean() : 변환한 0과 1의 합을 구한 후에 데이터의 개수로 나눔
print('정확도 :', accuracy.numpy())

정확도 : 0.9035088
