<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/DeepNeuralNetwork_tf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [3]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [1],
              [1],
              [0]
], dtype = 'float32')

In [4]:
w11 = np.array([[1], [3]], dtype = 'float32')
b11 = np.array([0], dtype = 'float32')

In [5]:
w12 = np.array([[2], [4]], dtype = 'float32')
b12 = np.array([0], dtype = 'float32')

In [6]:
np.dot(X, w11) + b11

array([[0.],
       [3.],
       [1.],
       [4.]], dtype=float32)

In [7]:
np.dot(X, w12) + b12

array([[0.],
       [4.],
       [2.],
       [6.]], dtype=float32)

In [16]:
w0 = tf.Variable([[1, 2], [3, 4]], dtype = 'float32')
b0 = tf.Variable([[0, 0]], dtype = 'float32')

In [17]:
tf.matmul(X, w0) + b0

<tf.Tensor: id=61, shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [3., 4.],
       [1., 2.],
       [4., 6.]], dtype=float32)>

In [18]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=67, shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [20]:
w1 = tf.Variable([[5], [6]], dtype = 'float32')
b1 = tf.Variable([0], dtype = 'float32')
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=105, shape=(4, 1), dtype=float32, numpy=
array([[0.99592984],
       [0.9999764 ],
       [0.9998689 ],
       [0.9999815 ]], dtype=float32)>

# 본격적으로 DNN 계산

In [27]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [1],
              [1],
              [0]
], dtype = 'float32')

w0 = tf.Variable([[1, 2], [3, 4]], dtype = 'float32')
b0 = tf.Variable([[0, 0]], dtype = 'float32')
w1 = tf.Variable([[5], [6]], dtype = 'float32')
b1 = tf.Variable([0], dtype = 'float32')

optimizer = tf.train.AdamOptimizer(0.1)

for step in range(5000):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
    cost = -tf.reduce_mean(y * tf.log(hypothesis1) + (1 - y) * tf.log(1 - hypothesis1))
    grads = tape.gradient(cost, [w0, w1, b0, b1])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w0, w1, b0, b1]))

    if step % 100 == 0:
      print('*'*100)
      print('cost : {:.4f}\nw0 :\n{}\nw1 :\n{}'.format(cost, w0, w1))
      print('*'*100)

****************************************************************************************************
cost : 4.1008
w0 :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>
w1 :
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
****************************************************************************************************
****************************************************************************************************
cost : 0.5575
w0 :
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0565379, -4.4126105],
       [ 1.2810543,  3.0600321]], dtype=float32)>
w1 :
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.6855311],
       [3.8502128]], dtype=float32)>
****************************************************************************************************
****************************************

In [32]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
predict = tf.cast((tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)) > 0.5, dtype = 'float32')
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype = 'float32'))
print('정확도 :', accuracy.numpy())

정확도 : 1.0


In [36]:
arr = np.array([[0, 1]], dtype = 'float32')
predict = tf.cast((tf.sigmoid(tf.matmul(tf.sigmoid(tf.matmul(arr, w0) + b0), w1) + b1)) > 0.5, dtype = tf.float32)
predict.numpy()

array([[1.]], dtype=float32)

In [37]:
arr = np.array([[1, 1]], dtype = 'float32')
predict = tf.cast((tf.sigmoid(tf.matmul(tf.sigmoid(tf.matmul(arr, w0) + b0), w1) + b1)) > 0.5, dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)