<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/iris_multi_class_tf2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [2]:
data = datasets.load_iris()
X = data.data
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = y.reshape(-1, 1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[ 1.05456482,  0.11163985,  0.52705983,  0.38267982],
       [-1.12729343, -1.62498003, -0.28528927, -0.28478498],
       [ 1.66063656,  0.3597284 ,  1.28138399,  0.78315871],
       [-1.36972213,  0.3597284 , -1.27171317, -1.35272867],
       [-0.52122169,  1.60017117, -1.32973811, -1.35272867],
       [-0.278793  , -0.1364487 ,  0.17891022,  0.1156939 ],
       [ 1.05456482,  0.60781696,  1.10730919,  1.18363759],
       [-0.40000735, -1.12880292,  0.35298502, -0.01779906],
       [-0.52122169,  0.85590551, -1.32973811, -1.08574275],
       [ 0.20606439, -2.12115713,  0.70113464,  0.38267982],
       [ 1.41820786,  0.3597284 ,  0.52705983,  0.24918686],
       [-0.278793  , -0.63262581,  0.6431097 ,  1.05014463],
       [-1.36972213,  0.3597284 , -1.44578798, -1.35272867],
       [-1.12729343,  1.35208262, -1.38776304, -1.48622163],
       [ 2.50913699,  1.84825972,  1.51348374,  1.05014463],
       [ 1.29699352,  0.11163985,  0.6431097 ,  0.38267982],
       [-1.00607908,  0.

In [7]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y)
enc.transform(y_train).toarray()

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [8]:
y_train_onehot = np.array(enc.transform(y_train).toarray(), dtype = 'float32')
y_test_onehot = np.array(enc.transform(y_test).toarray(), dtype = 'float32')

In [9]:
model = Sequential()
model.add(Dense(16, input_dim = 4, activation = 'sigmoid'))
model.add(Dense(3, activation='softmax'))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss = 'categorical_crossentropy', optimizer = Adam(lr = 0.1), metrics= ['acc'])
model.fit(X_train, y_train_onehot, epochs = 1000)

Epoch 1/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0975 - acc: 0.4833
Epoch 2/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.5877 - acc: 0.8083
Epoch 3/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.4139 - acc: 0.8083
Epoch 4/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.3415 - acc: 0.8917
Epoch 5/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2794 - acc: 0.8833
Epoch 6/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2288 - acc: 0.9250
Epoch 7/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2107 - acc: 0.9000
Epoch 8/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1537 - acc: 0.9583
Epoch 9/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1137 - acc: 0.9750
Epoch 10/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0906 - acc: 0.9833
Epoch 11/1000
4/4 [==============================] - 0s 2ms/step - lo

In [12]:
X_test = scaler.transform(X_test) 
# hypothesis0 = tf.sigmoid(tf.matmul(X_test, w0) + b0)
# predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict = model.predict(X_test)
# predict 최대값의 인덱스를 리턴
predict01 = np.argmax(predict, 1)
target = np.argmax(y_test_onehot, 1)
predict02 = (predict01 == target)
accuracy = np.sum(predict02)/len(predict02)
print('정확도')
print(accuracy)

정확도
0.9
