<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/iris_multi_class_tf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf
tf.enable_eager_execution()

In [3]:
data = datasets.load_iris()
data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [4]:
X = np.array(data.data, dtype = 'float32')
y = data.target.reshape(-1, 1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [6]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [7]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
# y가 몇가지 종류인지를 파악
enc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [8]:
# y값을 총 3가지로 OneHotEncoding
enc.transform(y_train).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0

In [9]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot = np.array(y_train_onehot, dtype = 'float32')

In [10]:
y_test

array([[2],
       [0],
       [1],
       [0],
       [2],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2],
       [1],
       [1],
       [0],
       [2],
       [2],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [2],
       [0]])

In [11]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot = np.array(y_test_onehot, dtype = 'float32')

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
X_train = scaler.transform(X_train)

In [14]:
initializer = tf.contrib.layers.xavier_initializer()
w0 = tf.Variable(initializer([4, 16]))
b0 = tf.Variable(initializer([16]))
w1 = tf.Variable(initializer([16, 3]))
b1 = tf.Variable(initializer([3]))

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [15]:
optimizer = tf.train.AdamOptimizer(0.1)

In [16]:
for step in range(1000):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
    cost = -tf.reduce_sum(y_train_onehot * tf.log(hypothesis1)) / len(hypothesis1)
    grads = tape.gradient(cost, [w0, w1, b0, b1])

    optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))

    if step % 100 == 0:
      print('-'*50)
      print('step: {}, cost:\n{:.6f}'.format(step, cost.numpy()))
      print('-'*50)

--------------------------------------------------
step: 0, cost:
0.540258
--------------------------------------------------
--------------------------------------------------
step: 100, cost:
0.000014
--------------------------------------------------
--------------------------------------------------
step: 200, cost:
0.000012
--------------------------------------------------
--------------------------------------------------
step: 300, cost:
0.000011
--------------------------------------------------
--------------------------------------------------
step: 400, cost:
0.000010
--------------------------------------------------
--------------------------------------------------
step: 500, cost:
0.000008
--------------------------------------------------
--------------------------------------------------
step: 600, cost:
0.000007
--------------------------------------------------
--------------------------------------------------
step: 700, cost:
0.000006
-----------------------------

In [17]:
X_test = scaler.transform(X_test)
hypothesis0 = tf.sigmoid(tf.matmul(X_test, w0) + b0)
predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict01 = tf.argmax(predict, 1)
target = tf.argmax(y_test_onehot, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype = 'float32'))
print('accuracy')
print(accuracy.numpy())

accuracy
0.96666664
