<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/multi_class_mammal_tf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf
tf.enable_eager_execution()

In [4]:
# [털, 날개]
X = np.array([
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 0],
    [0, 1]]
, dtype = 'float32')

# [기타, 포유류, 조류]
y = np.array([
              [1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [1, 0, 0],
              [0, 0, 1]
], dtype = 'float32')

In [5]:
# w와 b를 초기화 시키는 객체
initializer = tf.contrib.layers.xavier_initializer()

# 2줄 10칸의 w0를 생성해서 리턴
w0 = tf.Variable(initializer([2, 10]))
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[-0.4175783 , -0.06171697,  0.6162849 ,  0.4355275 ,  0.15203786,
        -0.6821516 , -0.37061357, -0.47303683,  0.65204173, -0.09030688],
       [-0.52914524, -0.1592561 ,  0.01566511, -0.40426397, -0.13233286,
        -0.42604142,  0.4311388 ,  0.42323035, -0.16827941,  0.23354733]],
      dtype=float32)>

In [6]:
b0 = tf.Variable(initializer([10]))
b0

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([-0.12048748,  0.29545778,  0.36400592, -0.5396929 ,  0.14219958,
       -0.42671496,  0.34831977, -0.29584318, -0.1431146 , -0.25261593],
      dtype=float32)>

In [7]:
w1 = tf.Variable(initializer([10, 3]))
b1 = tf.Variable(initializer([3]))

In [8]:
tf.matmul(X, w0) + b0

<tf.Tensor: id=61, shape=(5, 10), dtype=float32, numpy=
array([[-0.12048748,  0.29545778,  0.36400592, -0.5396929 ,  0.14219958,
        -0.42671496,  0.34831977, -0.29584318, -0.1431146 , -0.25261593],
       [-0.5380658 ,  0.2337408 ,  0.98029083, -0.10416538,  0.29423743,
        -1.1088666 , -0.02229381, -0.76888   ,  0.5089271 , -0.3429228 ],
       [-1.067211  ,  0.07448471,  0.99595594, -0.50842935,  0.16190457,
        -1.534908  ,  0.408845  , -0.34564966,  0.34064773, -0.10937548],
       [-0.12048748,  0.29545778,  0.36400592, -0.5396929 ,  0.14219958,
        -0.42671496,  0.34831977, -0.29584318, -0.1431146 , -0.25261593],
       [-0.6496327 ,  0.13620168,  0.37967104, -0.94395685,  0.00986671,
        -0.8527564 ,  0.7794586 ,  0.12738717, -0.311394  , -0.0190686 ]],
      dtype=float32)>

In [9]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=67, shape=(5, 10), dtype=float32, numpy=
array([[0.46991453, 0.5733318 , 0.5900098 , 0.36825904, 0.5354901 ,
        0.39491105, 0.5862101 , 0.42657396, 0.4642823 , 0.43717974],
       [0.36863765, 0.5581706 , 0.72716594, 0.4739822 , 0.5730332 ,
        0.24808228, 0.4944268 , 0.31672144, 0.62455493, 0.41509968],
       [0.25593382, 0.51861256, 0.7302627 , 0.3755618 , 0.5403879 ,
        0.17727673, 0.6008109 , 0.41443777, 0.58434784, 0.47268337],
       [0.46991453, 0.5733318 , 0.5900098 , 0.36825904, 0.5354901 ,
        0.39491105, 0.5862101 , 0.42657396, 0.4642823 , 0.43717974],
       [0.34307235, 0.5339979 , 0.59379375, 0.28010178, 0.5024667 ,
        0.29885498, 0.6855634 , 0.5318038 , 0.4227745 , 0.495233  ]],
      dtype=float32)>

In [10]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=72, shape=(5, 3), dtype=float32, numpy=
array([[0.28965208, 0.19086848, 0.51947945],
       [0.27646866, 0.12282573, 0.6007056 ],
       [0.24316765, 0.13433737, 0.622495  ],
       [0.28965208, 0.19086848, 0.51947945],
       [0.25334376, 0.20229813, 0.5443581 ]], dtype=float32)>

In [11]:
cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1)
cost

<tf.Tensor: id=80, shape=(), dtype=float32, numpy=1.1314611>

In [12]:
optimizer = tf.train.AdamOptimizer(0.01)

In [14]:
for step in range(1001):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
    hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
    cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1)
    grads = tape.gradient(cost, [w0, w1, b0, b1])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))

    if step % 100 == 0:
      print('='*50)
      print('step: {}, cost:\n{}'.format(step, cost.numpy()))
      print('='*50)

step: 0, cost:
1.1080396175384521
step: 100, cost:
0.3113147020339966
step: 200, cost:
0.05036880448460579
step: 300, cost:
0.018296241760253906
step: 400, cost:
0.009453849866986275
step: 500, cost:
0.005783686880022287
step: 600, cost:
0.003912525717169046
step: 700, cost:
0.0028295794036239386
step: 800, cost:
0.0021454908419400454
step: 900, cost:
0.00168460828717798
step: 1000, cost:
0.001358583802357316


In [18]:
predict = tf.nn.softmax(tf.matmul(tf.sigmoid(tf.matmul(X, w0) + b0), w1) + b1)
np.round(predict, 3)

array([[0.999, 0.001, 0.   ],
       [0.001, 0.997, 0.001],
       [0.   , 0.001, 0.999],
       [0.999, 0.001, 0.   ],
       [0.001, 0.   , 0.999]], dtype=float32)

In [19]:
# predict 최대값의 인덱스를 리턴
predict01 = tf.argmax(predict, 1)
predict01

<tf.Tensor: id=82377, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2])>

In [20]:
target = tf.argmax(y, 1)
target

<tf.Tensor: id=82380, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2])>

In [21]:
ac01 = tf.equal(predict01, target)
ac01

<tf.Tensor: id=82381, shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [22]:
ac02 = tf.cast(ac01, dtype = 'float32')
ac02

<tf.Tensor: id=82382, shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [23]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=82384, shape=(), dtype=float32, numpy=1.0>

In [24]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype = 'float32'))
print('accuracy')
print(accuracy.numpy())

accuracy
1.0
