<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import numpy as np

In [3]:
# hello의 one hot 인코딩
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
X = np.array([h], dtype = np.float32)
X

array([[1., 0., 0., 0.]], dtype=float32)

In [5]:
Wxh = np.array([[1], [2], [3], [4]], dtype = 'float32')
Wxh

array([[1.],
       [2.],
       [3.],
       [4.]], dtype=float32)

In [6]:
b = np.array([5], dtype = 'float32')
b

array([5.], dtype=float32)

In [7]:
h0 = np.dot(X, Wxh) + b
h0

array([[6.]], dtype=float32)

In [8]:
h0 = np.tanh(h0)
h0

array([[0.9999877]], dtype=float32)