<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [3]:
import numpy as np

# RNN simple one cell

In [4]:
# hello의 one hot 인코딩
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [5]:
X = np.array([h], dtype = np.float32)
X

array([[1., 0., 0., 0.]], dtype=float32)

In [6]:
Wxh = np.array([[1], [2], [3], [4]], dtype = 'float32')
Wxh

array([[1.],
       [2.],
       [3.],
       [4.]], dtype=float32)

In [7]:
b = np.array([5], dtype = 'float32')
b

array([5.], dtype=float32)

In [8]:
h0 = np.dot(X, Wxh) + b
h0

array([[6.]], dtype=float32)

In [9]:
h0 = np.tanh(h0)
h0

array([[0.9999877]], dtype=float32)

# RNN simple two cell

In [10]:
X = np.array([h, e], dtype = np.float32)
Wxh = np.array([[1], [2], [3], [4]], dtype = 'float32')
b = np.array([5], dtype = 'float32')
whh = np.array([.1], dtype = 'float32')

In [12]:
h0 = np.dot(X[0], Wxh) + b
h0 = np.tanh(h0)
h0

array([0.9999877], dtype=float32)

In [14]:
h1 = np.dot(X[1], Wxh) + b
h1 = h1 + np.dot(h0, whh)
h1 = np.tanh(h1)
h1

array([0.9999986], dtype=float32)