<a href="https://colab.research.google.com/github/Normal-case/DeepLearning/blob/master/XOR_operator_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

In [2]:
y = np.array([
              [0],
              [1],
              [1],
              [0]
], dtype = 'float32')

In [3]:
w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

In [4]:
np.dot(X, w) + b 

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [5]:
def sigmoid(h):
  return 1 / (1 + np.exp(-h))

In [6]:
hypothesis = np.dot(X, w) + b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [7]:
hypothesis = sigmoid(np.dot(X, w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [8]:
X_col_2d1 = X.T[0].reshape(1, -1)

In [16]:
w1_gred = 1/4 * np.dot(X_col_2d1, (hypothesis - y))
w1_gred

array([[0.2448853]], dtype=float32)

In [18]:
w1_gred = np.sum(w1_gred);
w1_gred

0.2448853

In [19]:
X_col_2d2 = X.T[1].reshape(1, -1)
w2_gred = 1/4 * np.sum(np.dot(X_col_2d2, (hypothesis - y)))
w2_gred

0.24770864844322205

In [22]:
import numpy as np
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

y = np.array([
              [0],
              [1],
              [1],
              [0]
], dtype = 'float32')

w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

def sigmoid(h):
  return 1 / (1 + np.exp(-h))

learning_rate = 0.1
for i in range(1000):
  for j in range(2):
    hypothesis = sigmoid(np.dot(X,w) + b)
    print('hypothesis :\n', hypothesis)
    cost = - 1/4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
    print('cost :\n', cost)
    X_col_2d = X.T[j].reshape(1, -1)
    w_gred = 1/4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
    w[j] = w[j] - learning_rate * w_gred
    b_gred = 1/4 * np.sum(hypothesis - y)
    b = b - learning_rate * b_gred

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [[0.4956542 ]
 [0.500909  ]
 [0.49823505]
 [0.50348985]]
cost :
 [[0.1711233 ]
 [0.17283273]
 [0.17417084]
 [0.17503785]]
hypothesis :
 [[0.4956649 ]
 [0.50091964]
 [0.49823493]
 [0.50348973]]
cost :
 [[0.17112859]
 [0.1728274 ]
 [0.1741709 ]
 [0.17503779]]
hypothesis :
 [[0.49567544]
 [0.50090265]
 [0.4982455 ]
 [0.50347275]]
cost :
 [[0.17113382]
 [0.17283587]
 [0.17416558]
 [0.17502923]]
hypothesis :
 [[0.4956861]
 [0.5009133]
 [0.4982454]
 [0.5034727]]
cost :
 [[0.1711391 ]
 [0.17283055]
 [0.17416565]
 [0.1750292 ]]
hypothesis :
 [[0.4956966 ]
 [0.5008964 ]
 [0.49825594]
 [0.50345576]]
cost :
 [[0.1711443 ]
 [0.172839  ]
 [0.17416035]
 [0.17502068]]
hypothesis :
 [[0.49570724]
 [0.50090706]
 [0.49825582]
 [0.5034557 ]]
cost :
 [[0.1711496 ]
 [0.17283368]
 [0.1741604 ]
 [0.17502065]]
hypothesis :
 [[0.49571767]
 [0.50089025]
 [0.49826628]
 [0.5034389 ]]
cost :
 [[0.17115474]
 [0.17284207]
 [0.17415516]
 [0.17501219]]
hypothesis :
 [[0.49572822]
 

In [23]:
predict = sigmoid(np.dot(X,w) + b)
predict = np.where(predict > 0.5, 1, 0)
predict = (predict == y)
accuracy = np.sum(predict) / 4
print('정확도 :', accuracy.round(2))

# 간단한 연산이지만 정확도가 낮은 이유??

정확도 : 0.5
